#!/usr/bin/env node
raptorLoggingConfig = {
    'ROOT': {level: 'WARN'},
    'oop-server': {level: 'WARN'},
    'resources': {level: 'WARN'}
}
        
require("../../init-raptor.js");
raptor.resources.addSearchPathDir(__dirname);
raptor.resources.addSearchPathDir(__dirname + '/..');
require("./test-app.js");